version: '2'
services:
  redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data/redis/
  web:
    build: ./web
    ports:
      - "8000:8000"
    volumes:
      - ./web/django/:/srv/django/

volumes:
  redis-data:
